# Generated by Django 2.1.5 on 2019-01-18 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import virtualspaces.spaces.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending Request'), (1, 'Accepted Request'), (2, 'Rejected Request'), (3, 'Canceled Request')], default=0)),
                ('full_day', models.BooleanField(default=False)),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('guests', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.Space')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to=virtualspaces.spaces.models.get_space_image_upload_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_images', to='spaces.Space')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
